### ISSUE TITLE
warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open

### ISSUE THREAD

**Issue by uzza1hossain** [flant/jekyll_include_plugin#4]

**Comment by nafg** [comment]
On Ruby 3.1.0 it fails with ` No such file or directory @ rb_sysopen` but when I added `URI.` it worked.

**Comment by ilya-lesikov** [comment]
https://github.com/flant/jekyll_include_plugin/pull/5 should've solved it.
